# Generated by Django 3.2 on 2021-04-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageextractor',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
