# Generated by Django 3.2 on 2021-04-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imageextractor_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageextractor',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
