# Generated by Django 3.2 on 2021-04-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_imageextractor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageextractor',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
