# Generated by Django 3.2 on 2021-04-14 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_imageextractor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageextractor',
            name='title',
        ),
    ]
