# Generated by Django 3.2 on 2021-04-14 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210415_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageWithCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classifiedcharacters')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imageextractor')),
            ],
        ),
    ]
