# Generated by Django 3.2 on 2021-04-15 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imagewithcharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageextractor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classifiedimage',
            name='classified_char',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classifiedcharacters'),
        ),
        migrations.AlterField(
            model_name='classifiedimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imageextractor'),
        ),
    ]
