# Generated by Django 3.2 on 2021-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210415_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedimage',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
